#!/usr/bin/env python3
"""Generate a pre-rotated 1-bit LVGL image with the fixed screen signature.

Output: config/boards/shields/lpm_view/widgets/edward_name.c

The lpm_view display is a portrait strip driven with rotation=1; upright
content must be pre-rotated with the same mapping as widgets/util.c
rotate_canvas(): logical (cx, cy) -> display (cy, W-1-cx).

Colour convention (matches widgets/picture/*.c, NICE_VIEW_WIDGET_INVERTED off):
palette index0 = black RGB, index1 = white RGB. On this panel LVGL pixel
value 0 renders white and value 1 renders black, so the INK pixels are bit 0
and the background bit 1 -> white text on black on screen.
"""

import re
import sys
import unicodedata

from PIL import Image, ImageDraw, ImageFont

TEXT = "爱德华"
FONT_PATH = r"C:\Windows\Fonts\simhei.ttf"
FONT_SIZE = 16
OUT = r"D:\Edward\Downloads\zmk-config-KEYPOINT-main\config\boards\shields\lpm_view\widgets\edward_name.c"
SYMBOL = "edward_name"

# ---- render upright ----
font = ImageFont.truetype(FONT_PATH, FONT_SIZE)
pad = 8
canvas = Image.new("L", (120, 40), 0)
d = ImageDraw.Draw(canvas)
d.text((pad, pad), TEXT, fill=255, font=font)
bbox = canvas.getbbox()  # ink bounding box
print("ink bbox:", bbox)
if bbox is None:
    sys.exit("no ink rendered")

up = canvas.crop(bbox)
# 1px margin
up_img = Image.new("L", (up.width + 2, up.height + 2), 0)
up_img.paste(up, (1, 1))
W, H = up_img.size  # upright width/height
print(f"upright: {W}x{H}")
if W > 70 or H > 20:
    sys.exit(f"too big: {W}x{H}")

px = up_img.load()

# ---- rotate: display(dx, dy) = upright(cx, cy), dx=cy, dy=W-1-cx ----
disp_w, disp_h = H, W  # display image is H wide, W tall
rot = [[0] * disp_w for _ in range(disp_h)]
for cx in range(W):
    for cy in range(H):
        if px[cx, cy] >= 128:  # ink
            rot[W - 1 - cx][cy] = 1  # ink -> bit 0 (set to 0 below)

# ---- emit C ----
rows = []
for dy in range(disp_h):
    line = rot[dy]
    for b in range((disp_w + 7) // 8):
        byte = 0xFF
        for i in range(8):
            dx = b * 8 + i
            if dx < disp_w and line[dx]:
                byte &= ~(0x80 >> i) & 0xFF  # ink clears the bit (index0)
        rows.append(byte)

data_size = 8 + len(rows)

def ascii_preview(grid, w):
    return "\n".join("".join("#" if v else "." for v in row[:w]) for row in grid)

print("--- rotated preview (display orientation, '#'=ink) ---")
print(ascii_preview(rot, disp_w))

c = f"""/*
 * Screen signature "{TEXT}", generated by tools/gen_name_img.py.
 * Pre-rotated for the lpm_view strip (rotation=1); ink is index 0 so it
 * renders white on the panel, background index 1 renders black.
 *
 * SPDX-License-Identifier: MIT
 */

#include <lvgl.h>

#ifndef LV_ATTRIBUTE_MEM_ALIGN
#define LV_ATTRIBUTE_MEM_ALIGN
#endif

const LV_ATTRIBUTE_MEM_ALIGN LV_ATTRIBUTE_LARGE_CONST uint8_t
    {SYMBOL}_map[] = {{
#if CONFIG_NICE_VIEW_WIDGET_INVERTED
        0xff, 0xff, 0xff, 0xff, /*Color of index 0*/
        0x00, 0x00, 0x00, 0xff, /*Color of index 1*/
#else
        0x00, 0x00, 0x00, 0xff, /*Color of index 0*/
        0xff, 0xff, 0xff, 0xff, /*Color of index 1*/

#endif

"""

for i in range(0, len(rows), 12):
    chunk = ", ".join(f"0x{b:02x}" for b in rows[i : i + 12])
    c += "        " + chunk + ",\n"

c += f"""}};
const lv_img_dsc_t {SYMBOL} = {{
    .header.cf = LV_IMG_CF_INDEXED_1BIT,
    .header.always_zero = 0,
    .header.reserved = 0,
    .header.w = {disp_w},
    .header.h = {disp_h},
    .data_size = {data_size},
    .data = {SYMBOL}_map,
}};
"""

with open(OUT, "w", encoding="utf-8") as f:
    f.write(c)
print(f"wrote {OUT} ({disp_w}x{disp_h}, {data_size} bytes)")
print(f"suggested placement: LV_ALIGN_TOP_LEFT x=140-{disp_w} -> x={140 - disp_w}, "
      f"y=(72-{disp_h})/2={ (72 - disp_h) // 2 }")
